### PR TITLE
update coursier action

### PR DESCRIPTION
**Pull request by pjfanning**
want to pick up https://github.com/coursier/cache-action/releases/tag/v6.4.5

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by laglangyue** [comment]
couchbase test failed

**Comment by mdedetrich** [comment]
> couchbase test failed

This can be flaky test but I will re-run to confirm

**Comment by mdedetrich** [comment]
Test confirmed to be flaky, safe to merge

**Pull request merged**
