### PR TITLE
Remove useless condition

### PR DESCRIPTION
**Pull request by mdedetrich**
image

### CODE REVIEW

**Comment by He-Pin** [comment]
Maybe the code is leaves for easy understanding ？

**Review by He-Pin — APPROVED** [review]
Lgtm

**Comment by mdedetrich** [comment]
> Maybe the code is leaves for easy understanding ？

Actually I thin its a mistake because it was manually translated from https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/MqttTopic.java#L253-L319

The main thing to be careful is that whether this inspection is correct (from first glance this does appear to be the case).

**Comment by mdedetrich** [comment]
Let me merge this PR myself, since we are dealing with mqtt I need to re-run the tests until the pass (just to make sure) and I will also wait for one more reviewer just to be safe.

**Comment by mdedetrich** [comment]
Okay all tests pass, lets wait for another review incase any one of us missed something.

**Review by nvollmar — APPROVED** [review]
lgtm

**Pull request merged**
