### PR TITLE
scalafmt 3.7.11

### PR DESCRIPTION
**Pull request by pjfanning**
matches other repos

### CODE REVIEW

**Comment by mdedetrich** [comment]
Can you separate the change to `jms/src/test/scala/docs/scaladsl/JmsConnectorsSpec.scala` in its own commit so it can be added distinctly into `.git-blame-ignore-revs`?

**Comment by mdedetrich** [comment]
Alternately I can do this ontop of your PR

**Comment by pjfanning** [comment]
the scalafmt change caused the change? it will fail the build if I separate it

**Comment by mdedetrich** [comment]
> the scalafmt change caused the change

Yes

>  it will fail the build if I separate it

No it wont as long as its in a single PR, I have done this all the time (i.e. see https://github.com/apache/incubator-pekko/pull/509/commits).

I also have a specific way of creating the format commit so its consistent with past formatting commits

**Review by He-Pin — APPROVED** [review]
Lgtm

**Comment by pjfanning** [comment]
@mdedetrich if you prefer

**Comment by mdedetrich** [comment]
Done https://github.com/apache/incubator-pekko-connectors/pull/219

**Pull request closed without merging**
