### PR TITLE
sshj 0.38.0

### PR DESCRIPTION
**Pull request by pjfanning**
see #304

### CODE REVIEW

**Comment by pjfanning** [comment]
@mdedetrich @kerr what do you think about the idea of including this in the pekko-connectors 1.0.2 release since it has a security impact? See https://github.com/apache/incubator-pekko-connectors/issues/304

**Review by mdedetrich — APPROVED** [review]
lgtm. I am fine with merging it for pekko-connectors 1.0.2 however would also like to get @He-Pin feedback

**Comment by He-Pin** [comment]
Supply chain security is always a concern,  and as we don't have a 1.1.x, we should fixed it in 1.0.x then.

**Review by He-Pin — APPROVED** [review]
Lgtm

**Pull request merged**
