### PR TITLE
[jms] close sessions when exceptions happen

### PR DESCRIPTION
**Pull request by pjfanning**
relates to #484

### CODE REVIEW

**Review by nvollmar — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
> relates to #484
> 
> not sure how straightforward this is to unit test - would probably involve opening up a lot of innards of the code

I would be more comfortable if we can somehow test this change as it would also allow us to account for regressions since being a resource leak its quite critical and we want to make sure that it works as intended.

**Review by He-Pin — APPROVED** [review]
Lgtm

As it close connection before reconnection

**Comment by pjfanning** [comment]
I'll try to add some test coverage. https://github.com/pjfanning/JmsWrapper is WIP

**Comment by pjfanning** [comment]
@mdedetrich the test change sin JmsProducerRetrySpec fail with the existing code and pass with the new code that closes the JMS sessions in the retriableException code path.

**Review by mdedetrich — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
I'll keep an eye on the tests because I suspect that the closes could be asynch and may need eventually blocks.

**Pull request merged**
