### PR TITLE
Replace mentions of Alpakka in code

### PR DESCRIPTION
**Pull request by mdedetrich**
Self explanatory

### CODE REVIEW

**Review by nvollmar — APPROVED** [review]
lgtm

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
Please let me merge this PR, I just want to make sure I don't create test regressions and some of the tests are naturally flaky

**Comment by pjfanning** [comment]
> Please let me merge this PR, I just want to make sure I don't create test regressions and some of the tests are naturally flaky

I support this PR, just worth retrying some of the failed runs before merging. Most seem to be some sort of Github CI issue (hopefully transient) but there might be 1 or 2 tests that still end up failing due to these changes.

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
