### PR TITLE
Revert "Update hbase-common, hbase-shaded-client to 1.7.2"

### PR DESCRIPTION
**Pull request by raboof**
Reverts apache/incubator-pekko-connectors#416

* https://github.com/apache/incubator-pekko-connectors/issues/61
* https://github.com/apache/incubator-pekko-connectors/discussions/443

### CODE REVIEW

**Review by pjfanning — APPROVED** [review]
Lgtm

**Review by pjfanning — COMMENTED** [review]
I am not an expert on Scala steward but it seems like the config changes might be wrong. I think it would work better to put these changes in the updates.ignore section since they don't specify versions - I think updates.pin is based on specifying a version or partial version.

**Review by mdedetrich — APPROVED** [review]
LGTM, but maybe we should pin it to 1.7.x instead of totally disabling hbase updates?

**Comment by raboof** [comment]
> I am not an expert on Scala steward but it seems like the config changes might be wrong. I think it would work better to put these changes in the updates.ignore section since they don't specify versions - I think updates.pin is based on specifying a version or partial version.

Ah, probably, updated

> LGTM, but maybe we should pin it to 1.7.x instead of totally disabling hbase updates?

If we don't have CI then I'm not sure we should make changes, including minor updates.

**Pull request merged**
