### PR TITLE
upgrade pekko libs and aws lib

### PR DESCRIPTION
**Pull request by pjfanning**
these jars support scala 3 (as a bonus)

### CODE REVIEW

**Comment by mdedetrich** [comment]
Did you release `AwsSpiPekkoHttp` for Scala 3?

**Comment by pjfanning** [comment]
> Did you release `AwsSpiPekkoHttp` for Scala 3?

the version in this PR has a v3 jar published

**Comment by mdedetrich** [comment]
Perfect!

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
