### PR TITLE
upgrade pekko-http-circe

### PR DESCRIPTION
**Pull request by pjfanning**
this version supports Scala3

### CODE REVIEW

**Comment by mdedetrich** [comment]
Hmm this library seems seriously out of date (hasn't been updated in 7 years), maybe we should consider replacing it with https://github.com/mdedetrich/akka-streams-json (I am planning to convert it to pekko, just waiting for https://github.com/typelevel/jawn/pull/537 https://github.com/typelevel/jawn/pull/535?

**Comment by pjfanning** [comment]
This lib is my fork of https://github.com/hseeberger/akka-http-json/releases and there are relatively recent releases.

This change can at least tide us over till we can replace pekko-http-circe with something else.

**Comment by mdedetrich** [comment]
Ah I mistook what you forked, okay will approve but I want to minimize the amount of forks we want to rely on (actually want to send a message on the mailing list about this because connectors seems to be a PITA in this regard).

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
