### PR TITLE
protect 1.0.x branch

### PR DESCRIPTION
**Pull request by pjfanning**
also updates job for 1.0 doc publishing to use v1.0.2 (latest release)

### CODE REVIEW

**Comment by mdedetrich** [comment]
@pjfanning One PR that is relevant for `1.0.x` just landed in `main`, can you rebase? Otherwise we have to a cherry pick of a commit

**Comment by pjfanning** [comment]
I'll delay adding this and will be rebase 1.0.x - the PR that I want to merge now is #326

**Comment by mdedetrich** [comment]
CI seems to be failing for some reason?

**Comment by pjfanning** [comment]
> CI seems to be failing for some reason?

Worked when I rebuilt. The issue appears that the mima checks ran while the 1.0.2 jars were partially copied into maven central.

**Comment by pjfanning** [comment]
@mdedetrich could you re-review?

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
