### PR TITLE
sbt-source-dist 0.1.10

### PR DESCRIPTION
**Pull request by pjfanning**
switches to just publishing a tgz release (no zip)

### CODE REVIEW

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by He-Pin** [comment]
tgz seems not easy to uncompress on Windows PC.

**Comment by pjfanning** [comment]
> tgz seems not easy to uncompress on Windows PC.

Unfortunately, that is a Windows problem - there must be a tool that you can install on Windows that can untar a file. I haven't used Windows in many many years. I used to use WinZip and it covered all sorts of archive formats.

**Comment by He-Pin** [comment]
Let's follow the ASF rule, haozip can do this or 7zip.

**Comment by mdedetrich** [comment]
> tgz seems not easy to uncompress on Windows PC.

7zip is a program which you can use to decompress tgz files.

I am personally not that pushy when it comes to removing zip support, it was originally suggested as a solution due to a specific test but it turns out the test also has issues with the tgz archive.

**Comment by He-Pin** [comment]
image
@pjfanning Can we provide both?

**Comment by pjfanning** [comment]
> image @pjfanning Can we provide both?

I don't understand how netty4 affects this sbt plugin PR. Is this meant for another PR?

**Comment by pjfanning** [comment]
The discussion was at https://lists.apache.org/thread/s4omnkqxnlsmm7hv4g18q9m4ho5kkdjr and not producing 2 release archives was actually suggested by Ryan Skraba on one of our release votes. The fact that there are some test issues when using the pekko http releases is not the main reason. It saves release effort and voting effort.

**Comment by He-Pin** [comment]
@pjfanning I see.

**Pull request merged**
