### PR TITLE
pekko-http 1.0.0

### PR DESCRIPTION
**Pull request by pjfanning**
and update other jars that need updating because of pekko-http release

### CODE REVIEW

**Comment by mdedetrich** [comment]
> still needs pekko-http-circe to be published

Already done as v1.0.0 https://github.com/mdedetrich/pekko-streams-circe/actions/runs/5739049631/job/15553937918

**Comment by mdedetrich** [comment]
@pjfanning If you want to wait till tonight, pekko-connectors-kafka will also be released (unless there are any problems) so you can also update that in this PR.

**Comment by pjfanning** [comment]
@mdedetrich no rush on this - it's just useful to get a CI build to see what is broken - we can wait till kafka plugi is released and upgrade that in this in PR too.

**Comment by pjfanning** [comment]
Now includes the Connectors Kafka release uptake.

**Comment by pjfanning** [comment]
@mdedetrich would you have time to review this? I'm trying to get together a new set of snapshots for https://cwiki.apache.org/confluence/display/PEKKO/Testing+with+Pekko+Snapshot+Jars

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
