### PR TITLE
Update Pekko

### PR DESCRIPTION
**Pull request by mdedetrich**
Updates Pekko to 1.0.2

### CODE REVIEW

**Comment by mdedetrich** [comment]
@pjfanning Was there some change in Pekko 1.0.2 that would cause pekko-connectors to fail to compile, specifically for the xml module?

**Comment by pjfanning** [comment]
> @pjfanning Was there some change in Pekko 1.0.2 that would cause pekko-connectors to fail to compile, specifically for the xml module?

not sure why this is happening but the logs don't highlight a compile issue, maybe there is a compile warning now and the build is set up to fail with compile warnings?

**Comment by mdedetrich** [comment]
> not sure why this is happening but the logs don't highlight a compile issue, maybe there is a compile warning now and the build is set up to fail with compile warnings?

Let me confirm this then, it's suspicious that the build fail didn't occur in the PR that changed the compile warnings.

**Comment by mdedetrich** [comment]
Okay so the nowarning's did fix the issue, everything is good now

**Review by pjfanning — APPROVED** [review]
lgtm

**Pull request merged**
