### PR TITLE
add 2024 to copyright

### PR DESCRIPTION
**Pull request by pjfanning**

### CODE REVIEW

**Review by rudransh61 — COMMENTED** [review]
nice buddy 
can you do this for
https:://github.com/rudransh61/NextGenCSS-

**Comment by rudransh61** [comment]
Also , keep this in mind that 
the licence will be applied from the year written in file to till now

so, id think you should change the year

**Comment by rudransh61** [comment]
you should change it if there is a significant development in that year

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
