### PR TITLE
Update Scala 2 versions

### PR DESCRIPTION
**Pull request by mdedetrich**
Self explanatory

### CODE REVIEW

**Comment by He-Pin** [comment]
2023-06-06T17:15:27.1276171Z [0m[[0m[31merror[0m] [0m[0m	at java.base/java.lang.Thread.run(Thread.java:829)[0m

**Comment by He-Pin** [comment]
```
[error] (Scalaunidoc / doc) java.net.URISyntaxException: Illegal character in path at index 143: [https://github.com/apache/incubator-pekko-connectors/tree/main/google-common/src/main/scala/org/apache/pekko/stream/connectors/google/scaladsl/`X-Upload-Content-Type`.scala#L27](https://github.com/apache/incubator-pekko-connectors/tree/main/google-common/src/main/scala/org/apache/pekko/stream/connectors/google/scaladsl/%60X-Upload-Content-Type%60.scala#L27)
```

**Comment by mdedetrich** [comment]
> > 
> 
> [error] (Scalaunidoc / doc) java.net.URISyntaxException: Illegal character in path at index 143: [https://github.com/apache/incubator-pekko-connectors/tree/main/google-common/src/main/scala/org/apache/pekko/stream/connectors/google/scaladsl/`X-Upload-Content-Type`.scala#L27](https://github.com/apache/incubator-pekko-connectors/tree/main/google-common/src/main/scala/org/apache/pekko/stream/connectors/google/scaladsl/%60X-Upload-Content-Type%60.scala#L27)

 I think this is a Scala 2 bug, re-running CI but will probably have to report upstream

**Review by He-Pin — APPROVED** [review]
lgtm

**Comment by mdedetrich** [comment]
@He-Pin Its still failing but I am trying to see if there is a quick workaround

**Comment by mdedetrich** [comment]
Issue created upstream at https://github.com/scala/bug/issues/12846

**Comment by mdedetrich** [comment]
The latest released Scala 2.13.12 was released with the upstream bug fixed. Merging

**Pull request merged**
